apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.name }}
spec:
  provider:
    oracle:
      vault: {{ required "vault is required" .Values.vault | quote }}
      region: {{ required "region is required" .Values.region | quote }}
      principalType: InstancePrincipal
      {{- with .Values.compartment }}
      compartment: {{ . | quote }}
      {{- end }}
      {{- with .Values.encryptionKey }}
      encryptionKey: {{ . | quote }}
      {{- end }}
